[package]
name = "rquest"
version = "0.33.6"
description = "An ergonomic, all-in-one JA3/JA4/HTTP2 fingerprint HTTP/WebSocket client"
keywords = ["http", "client", "websocket", "ja3", "ja4"]
categories = ["web-programming::http-client"]
repository = "https://github.com/penumbra-x/rquest"
documentation = "https://docs.rs/rquest"
authors = ["0x676e67 <gngppz@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.80"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["boring-tls", "boring-tls-webpki-roots"]

full = [
    "boring-tls",
    "json",
    "stream",
    "cookies",
    "socks",
    "gzip",
    "brotli",
    "zstd",
    "deflate"
]

websocket = ["async-tungstenite", "tokio-util/compat"]

cookies = ["cookie_crate", "cookie_store"]

gzip = ["async-compression", "async-compression/gzip", "tokio-util"]

brotli = ["async-compression", "async-compression/brotli", "tokio-util"]

zstd = ["async-compression", "async-compression/zstd", "tokio-util"]

deflate = ["async-compression", "async-compression/zlib", "tokio-util"]

json = ["serde_json"]

multipart = ["mime_guess"]

hickory-dns = ["hickory-resolver"]

stream = ["tokio/fs", "tokio-util"]

socks = ["tokio-socks"]

boring-tls-native-roots = ["dep:rustls-native-certs"]
boring-tls-webpki-roots = ["dep:webpki-root-certs"]

# BoringSSL PQ experimental features
boring-tls-pq = ["boring/pq-experimental"]

# Optional disable internal proxy cache
internal_proxy_sys_no_cache = []

# Internal (PRIVATE!) features used to aid testing.
# Don't rely on these whatsoever. They may disappear at anytime.

# Enables common types used for TLS. Useless on its own.
boring-tls = [
    "dep:boring",
    "dep:tokio-boring",
    "dep:boring-sys",
    "dep:foreign-types",
    "dep:flate2",
    "dep:brotli",
    "dep:zstd",
    "dep:linked_hash_set",
    "dep:tower-layer",
    "dep:antidote",
    "dep:typed-builder",
    "boring-tls-pq"
]

[dependencies]
base64 = "0.22"
http = "0.2"
url = "2.5"
bytes = "1.0"
serde = "1.0"
serde_urlencoded = "0.7.1"
tower-service = "0.3"
futures-core = { version = "0.3.0", default-features = false }
futures-util = { version = "0.3.0", default-features = false }

# Optional deps...

## json
serde_json = { version = "1.0", optional = true }
## multipart
mime_guess = { version = "2.0", default-features = false, optional = true }

encoding_rs = "0.8"
http-body = "0.4.6"
hyper = { package = "hyper2", version = "0.14.80", default-features = false, features = [
    "http1",
    "http2",
    "client",
    "runtime",
] }
log = "0.4"
mime = "0.3.17"
percent-encoding = "2.3"
tokio = { version = "1", default-features = false, features = ["net", "time"] }
pin-project-lite = "0.2.0"
ipnet = "2.10.0"

# Optional deps...

## boring-tls
boring = { package = "boring2", version = "4", optional = true }
boring-sys = { package = "boring-sys2", version = "4", optional = true }
tokio-boring = { package = "tokio-boring2", version = "4", optional = true }
foreign-types = { version = "0.5.0", optional = true }

# cert compression
brotli = { version = "7", optional = true }
flate2 = { version = "1", optional = true }
zstd = { version = "0.13", optional = true }

# tls root certs
rustls-native-certs = { version = "0.8.0", optional = true }
webpki-root-certs = { version = "0.26.0", optional = true }

# boring-tls session cache
linked_hash_set = { version = "0.1", optional = true }
tower-layer = { version = "0.3", optional = true }
antidote = { version = "1", optional = true }

# boring-tls extension builder
typed-builder = { version = "0.20.0", optional = true }

## cookies
cookie_crate = { version = "0.18", package = "cookie", optional = true }
cookie_store = { version = "0.21", optional = true }

## compression
async-compression = { version = "0.4.0", default-features = false, features = [
    "tokio",
], optional = true }
tokio-util = { version = "0.7", default-features = false, features = [
    "codec",
    "io",
], optional = true }

## socks
tokio-socks = { version = "0.5.2", optional = true }

## websocket
async-tungstenite = { version = "0.28.0", optional = true }

## hickory-dns
hickory-resolver = { version = "0.24", optional = true }

[target.'cfg(windows)'.dependencies]
windows-registry = "0.3.0"

[target.'cfg(target_os = "macos")'.dependencies]
system-configuration = "0.6.0"

[dev-dependencies]
env_logger = "0.10.0"
hyper = { package = "hyper2", version = "0.14.80", default-features = false, features = [
    "stream",
    "http1",
    "http2",
    "client",
    "server",
    "runtime",
] }
serde = { version = "1.0", features = ["derive"] }
libflate = "2.0.0"
zstd = { version = "0.13" }
doc-comment = "0.3"
tokio = { version = "1.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
futures = { version = "0.3.0", default-features = false }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "charset", "http2", "macos-system-configuration"]}

[[example]]
name = "json_dynamic"
path = "examples/json_dynamic.rs"
required-features = ["json"]

[[example]]
name = "json_typed"
path = "examples/json_typed.rs"
required-features = ["json"]

[[example]]
name = "tor_socks"
path = "examples/tor_socks.rs"
required-features = ["socks"]

[[example]]
name = "form"
path = "examples/form.rs"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "impersonate"
path = "examples/impersonate.rs"

[[example]]
name = "hickory_dns"
path = "examples/hickory_dns.rs"
required-features = ["hickory-dns"]

[[example]]
name = "headers_order"
path = "examples/headers_order.rs"
required-features = ["cookies"]

[[example]]
name = "impersonate_skip_headers"
path = "examples/impersonate_skip_headers.rs"

[[example]]
name = "impersonate_psk"
path = "examples/impersonate_psk.rs"

[[example]]
name = "set_headers"
path = "examples/set_headers.rs"

[[example]]
name = "set_cookies"
path = "examples/set_cookies.rs"
required-features = ["cookies"]

[[example]]
name = "set_cookie_provider"
path = "examples/set_cookie_provider.rs"
required-features = ["cookies"]

[[example]]
name = "set_proxies"
path = "examples/set_proxies.rs"
required-features = ["socks", "brotli"]

[[example]]
name = "set_local_address"
path = "examples/set_local_address.rs"
required-features = ["brotli"]

[[example]]
name = "set_interface"
path = "examples/set_interface.rs"
required-features = ["brotli"]

[[example]]
name = "set_native_root_cert"
path = "examples/set_native_root_cert.rs"
required-features = ["boring-tls-native-roots"]

[[example]]
name = "set_webpki_root_cert"
path = "examples/set_webpki_root_cert.rs"
required-features = ["boring-tls-webpki-roots"]

[[example]]
name = "websocket"
path = "examples/websocket.rs"
required-features = ["websocket", "futures-util/std"]

[[example]]
name = "websocket_via_proxy"
path = "examples/websocket_via_proxy.rs"
required-features = ["websocket", "futures-util/std", "socks"]

[[test]]
name = "cookie"
path = "tests/cookie.rs"
required-features = ["cookies"]

[[test]]
name = "gzip"
path = "tests/gzip.rs"
required-features = ["gzip"]

[[test]]
name = "brotli"
path = "tests/brotli.rs"
required-features = ["brotli"]

[[test]]
name = "deflate"
path = "tests/deflate.rs"
required-features = ["deflate"]

[[test]]
name = "multipart"
path = "tests/multipart.rs"
required-features = ["multipart"]

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["full"]

[[example]]
name = "redirect_via_proxy"
path = "examples/redirect_via_proxy.rs"
required-features = ["full"]

[[example]]
name = "redirect_with_request"
path = "examples/redirect_with_request.rs"
required-features = ["full"]

[[example]]
name = "set_redirect"
path = "examples/set_redirect.rs"
required-features = ["full"]

[[example]]
name = "base_url"
path = "examples/base_url.rs"

[[example]]
name = "cookie_store_with_request"
path = "examples/cookie_store_with_request.rs"
required-features = ["cookies"]
